---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: dataverse
  labels:
    app.kubernetes.io/name: dataverse
    app.kubernetes.io/version: "5.4.1"
    app.kubernetes.io/component: appserver
    app.kubernetes.io/part-of: dataverse
    app.kubernetes.io/managed-by: kubectl
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dataverse
      app.kubernetes.io/part-of: dataverse
      app.kubernetes.io/component: appserver
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dataverse
        app.kubernetes.io/part-of: dataverse
        app.kubernetes.io/component: appserver
    spec:
      containers:
        - name: dataverse
          image: steinsteiny/dataverse:5.4.1
          imagePullPolicy: Always
          resources:
            requests:
              memory: "2Gi"
            limits:
              memory: "4Gi"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: dataverse
          env:

            - name: DATAVERSE_DB_HOST
              value: postgresql
            - name: DATAVERSE_DB_USER
              value: dataverse
            - name: DATAVERSE_DB_PASSWORD
              value: changeme
            - name: DATAVERSE_DB_NAME
              value: dataverse
            - name: POSTGRES_PASSWORD
              value: changeme           
            - name: POSTGRES_SERVER
              value: postgresql

            - name: SOLR_LOCATION
              value: solr:8983

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: dataverse-postgresql
                  key: username
                  optional: true
            - name: POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: dataverse-postgresql
                  key: database
                  optional: true
          volumeMounts:
            - name: files
              mountPath: /data
            - name: docroot
              mountPath: /opt/docroot
            - name: heapdumps
              mountPath: /dumps
            - name: db-secret
              mountPath: "/secrets/db"
              readOnly: true
            - name: doi-secret
              mountPath: "/secrets/doi"
              readOnly: true
            # This is here because of IQSS/dataverse-kubernetes#177. TBR for #178
            - name: primefaces-upload
              mountPath: /opt/dataverse/appserver/glassfish/domains/domain1/generated/jsp/dataverse
          readinessProbe:
            httpGet:
              path: /robots.txt
              port: 8080
      initContainers:
        - name: volume-mount-hack
          image: giantswarm/tiny-tools
          command: ["sh", "-c", "chown -c 1000:1000 /data /opt/docroot /uploads"]
          volumeMounts:
            - name: files
              mountPath: /data
            - name: docroot
              mountPath: /opt/docroot
            # This is here because of IQSS/dataverse-kubernetes#177. TBR for #178
            - name: primefaces-upload
              mountPath: /uploads
        - name: check-db-ready
          image: postgres:9.6
          command: ['sh', '-c',
            'until pg_isready -h "${POSTGRESQL_SERVICE_HOST}" -p "${POSTGRESQL_SERVICE_PORT}";
            do echo waiting for database; sleep 3; done;']
        - name: check-solr-ready
          image: giantswarm/tiny-tools
          command: ['sh', '-c',
            'until curl -sS -f "http://${SOLR_SERVICE_HOST}:${SOLR_SERVICE_PORT}/solr/collection1/admin/ping" 2>&1 | grep "status.:.OK";
            do echo waiting for solr; sleep 3; done;']
      volumes:
        - name: files
          persistentVolumeClaim:
            claimName: dataverse-files
        - name: docroot
          persistentVolumeClaim:
            claimName: dataverse-docroot
        - name: db-secret
          secret:
            secretName: dataverse-postgresql
        - name: doi-secret
          secret:
            secretName: dataverse-doi
        - name: heapdumps
          emptyDir: {}
        # This is here because of IQSS/dataverse-kubernetes#177. TBR for #178
        - name: primefaces-upload
          emptyDir: {}
